### ISSUE TITLE
Costume windows handling

### ISSUE THREAD

**Issue by DipStax** [DipStax/Engine#1]
## Explication:

Create a windows from scratch, manage some event and beeing able to draw simple shape.

## Todo

- [ ] Openning of the windows
- [ ] Closing of the windows
- [ ] Drawing pixel per pixel
- [ ] Drawing square
- [ ] Drawing circle

## Techno:

- WIN32 API
